version: '3.7'
services:

  postgres:
    restart: always
    image: postgres:10
    env_file:
      - ./.envs/.local/.dev.env
    ports:
      - '5432:5432'
    volumes:
      - supermapspointer-postgres:/var/lib/postgresql/data
    networks:
      - backend

  flask:
    build: .
    command: bash -c './utils/wait-for.sh postgres:5432 -- flask run --host=0.0.0.0 -p 8000 --no-debugger --no-reload --without-threads'
    depends_on:
      - postgres
    ports:
      - '8000:8000'
      - '3000:3000'
    volumes:
      - .:/back
    env_file:
      - ./.envs/.local/.dev.env
    networks:
      - backend

volumes:
  supermapspointer-postgres:

networks:
  backend:
    name: backend