version: '3.7'
services:

  postgres:
    image: postgres:10
    restart: on-failure
    env_file:
      - ./.envs/.local/.test.env
    ports:
      - '5432:5432'
    volumes:
      - supermapspointer-postgres:/var/lib/postgresql

  pytest:
    build: .
    command: bash -c './utils/wait-for.sh postgres:5432 -- pytest ./tests'
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    volumes:
      - .:/back
    env_file:
      - ./.envs/.local/.test.env

volumes:
  supermapspointer-postgres:


