version: '3'
services:

  postgres:
    restart: always
    image: postgres:10
    env_file:
      - .super_maps_pointer.env
    ports:
      - '5432:5432'
    volumes:
      - supermapspointer-postgres:/var/lib/postgresql/data
    networks:
      - backend

  web:
    build: .
    command: 'flask run --host=0.0.0.0 -p 8000 --no-debugger --no-reload'
    depends_on:
      - postgres
    ports:
      - '8000:8000'
      - '3000:3000'
    volumes:
      - .:/back
    env_file:
      - .super_maps_pointer.env
    networks:
      - backend

  # angular_app:
  #   build: 
  #     context: '../frontend'
  #   depends_on:
  #     - flask_app
  #   command: 'npm start'
  #   ports:
  #     - '4200:4200' 
  #     - '49153:49153'
  #   expose:
  #     - '4200'
  #     - '49153'
  #   volumes:
  #     - .:/super_maps_pointer
  #   networks:
  #     - frontend

volumes:
  supermapspointer-postgres:

networks:
  backend:
  # frontend: